### ISSUE TITLE
Detailed write-up

### ISSUE THREAD

**Issue by fesamper** [tailsu/miele-brain#2]
There is any way to get the Detailed write-up? There is no way to view it at reddit...
I'm interested to add an esp32 to my miele washing machine
Thanks

**Comment by tailsu** [comment]
I lost access to that subreddit and I have no other copy :/

**Comment by tailsu** [comment]
The subreddit is public again. https://www.reddit.com/r/esp8266/comments/msot24/i_implanted_a_brain_into_my_washing_machine/
